-- Supabase 测试结果表结构
-- 在 Supabase SQL 编辑器中运行此脚本创建表

-- 创建 test_results 表
CREATE TABLE IF NOT EXISTS test_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
  answers JSONB NOT NULL,
  recommendation_title TEXT NOT NULL,
  recommendation_description TEXT NOT NULL,
  recommendation_emoji TEXT NOT NULL,
  anonymized BOOLEAN NOT NULL DEFAULT true,
  device_info JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_test_results_timestamp ON test_results (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_test_results_session_id ON test_results (session_id);
CREATE INDEX IF NOT EXISTS idx_test_results_recommendation_title ON test_results (recommendation_title);
CREATE INDEX IF NOT EXISTS idx_test_results_anonymized ON test_results (anonymized);

-- 为 API 访问设置行级安全策略（RLS）
ALTER TABLE test_results ENABLE ROW LEVEL SECURITY;

-- 创建允许服务角色访问的策略（用于后端API）
CREATE POLICY "服务角色完全访问" ON test_results
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- 创建允许匿名用户插入数据的策略（如果前端需要直接访问）
-- 注意：生产环境建议仅通过后端API插入数据
CREATE POLICY "允许匿名用户插入数据" ON test_results
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- 创建允许匿名用户只读访问的策略（用于数据分析仪表板）
CREATE POLICY "允许匿名用户只读访问" ON test_results
  FOR SELECT
  TO anon
  USING (true);

-- 注释：如果需要更严格的访问控制，可以调整上述策略
-- 例如，只允许特定角色的用户查询数据